name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 120
    runs-on: "macOS-13"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@5b1a6c5ca98b5642996812781f6ad9b2d5935f85
      with:
        jvm: "temurin:17"
    - run: scala-cli Main.scala