name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 120
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@5b1a6c5ca98b5642996812781f6ad9b2d5935f85
      with:
        jvm: "temurin:17"
    - run: |
        sudo xcode-select -s "/Applications/Xcode_13.1.0.app" || ( ls /Applications; exit 1 )
        sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
    - run: brew install libsodium && brew link --overwrite libsodium
    - run: scala-cli Main.scala